### ISSUE TITLE
OpenJDK probs: Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by plooney** [unibas-gravis/GiNGR#2]
I had this issue on Ubuntu 20.04 with OpenJDK. 

Installing temerium-jdk fixed this issue

https://adoptium.net/

**Comment by madsendennis** [comment]
Thanks for highlighting this! I think this might come down to the scalismo version that is used, which relies on an old VTK version. The current version of scalismo can be a bit sensitive to the JDK version as you have also experienced.
There is a new scalismo release coming up which upgrades VTK from v6 to v9. 
I'll have this repo upgraded as well - hopefully, that'll solve the problem.
