### ISSUE TITLE
Coherent Point Drift for Rigid Registration

### ISSUE THREAD

**Issue by stevenagl12** [unibas-gravis/GiNGR#5]
How would you go about doing a rigid registration with your coherent point drift method?

**Comment by madsendennis** [comment]
An isolated implementation is available in the 'other' folder `https://github.com/unibas-gravis/GiNGR/blob/main/src/main/scala/other/algorithms/CPDRegistration.scala` where you can use the `RigidCPDRegistration` class.

The full GiNGR framework is focused and optimized for the the non-rigid aspect. To do rigid registration with GiNGR you would still need to supply a GPMM. This could be made very inflexible and then with a large observation uncertainty, then it would be approximately the rigid registration case - but rather slow.
